name: Import repo pipeline

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'The name of the repository to import'
        required: true


jobs:
  import-repo:
    runs-on: ubuntu-latest
    name: Import repo
    environment: import-${{ github.ref_name }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Just
        uses: extractions/setup-just@v2
        with:
          just-version: '1.4.0'

#      - name: Generate a token
#        uses: actions/create-github-app-token@v1
#        id: generate-token
#        with:
#          app-id: ${{ vars.APP_ID }}
#          private-key: ${{ secrets.APP_PRIVATE_KEY }}
#          owner: ${{ vars.OWNER }}

#      - name: Build binary
#        working-directory: feature/github-repo-importer
#        run: just build

      - name: Setup vars
        run: |
          echo "full_repo_name=${{ vars.OWNER }}/${{ github.event.inputs.repo_name }}" >> $GITHUB_ENV
          echo "automation_branch_name=import/${{ github.ref_name }}/${{ vars.OWNER }}/${{ github.event.inputs.repo_name }}" >> $GITHUB_ENV

      - name: Import repo
#        working-directory: feature/github-repo-importer
        run: echo $full_repo_name
#        env:
#          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push changes
        run: |
          git checkout -b $automation_branch_name
          git push --set-upstream origin $automation_branch_name
          git add .
          git commit -m "Auto-generated changes. Import $full_repo_name repository"
          git push
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Create Pull Request
        run: gh pr create --title "Import $full_repo_name" --body "This is an automated PR." --base ${{ github.ref_name }} --head $automation_branch_name
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}