name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    environment: release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Maven Central Repository
      uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c
#      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
#        distribution: 'temurin'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Release artifacts
      run: |
        pwd
        echo "first"
        ls -la /home
        echo "second"
        ls -la /home/runner
        echo "third"
        ls -la /home/runner/work
        echo "fourth"
        ls -la /home/runner/work/hello-world
        echo "fifth"
        ls -la /home/runner/work/hello-world/hello-world
        mvn --batch-mode deploy -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}