name: CI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    environment: release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Maven Central Repository
      uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c
#      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
#        distribution: 'temurin'
        server-id: ossrh
        server-username: ${{ secrets.OSSRH_USERNAME }}
        server-password: ${{ secrets.OSSRH_PASSWORD }}
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Release artifacts
      run: mvn --batch-mode deploy -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}